/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package invaders;

import invaders.jade.Window;

public class Main {
    public static void main(String[] args) {
        Window window = Window.get();
        window.run();
       
    }
}
